### ISSUE TITLE
Game crash while placing playerhopper

### ISSUE THREAD

**Issue by charmesal** [MoreThanHidden/PlayerHopper#6]
Game version: 1.15.2
Forge version: 1.15.2-forge-31.1.46
Mod version: playerhopper-1.15-1.2
Other mods installed: None
Latest.log: https://pastebin.com/CuzEwhLG
Crash log: https://pastebin.com/w4rncXgB

Game crashes once I place the player hopper

**Comment by MoreThanHidden** [comment]
Fixed on 1.14 will do on 1.15 this evening

**Comment by charmesal** [comment]
Great to hear. Take your time man. I appreciate the free mod and I know you devs have a life besides Minecraft mods.
